config/routes.rb
IOHBack::Application.routes.draw do
  root "home#index"
  get "home/index"
  get "speaker/index"
  get "speaker/new"
  get "talks/index"
  get "admin/index"
    
        
    resources :helpers
    resources :speakers
    resources :first_page
    resources :comments
    resources :process
    resources :home
    resources :admin
    resources :talks
          get 'talks/:id/edit#:category' => 'talks#edit' , :as =>"commenting"
          get 'talks:type' => 'talks#type'
          get 'talks/new/:id' => 'talks#new'
       
       
  devise_for :users
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :talk
	#has_many :userc, :useromments
	belongs_to :user # :through => :usercomment

	
	def self.get_by_talk(talk)
		allCommentsWithNames = Array.new
		allUserComments = Comment.where(:talk_id => talk.id)
		#are_owners = Usercomment.where(:comment_id=>Comment.where(:talk_id => talk.id).select(:id)).where(:role=>"owner")
		allUserComments.each do |f|
			allCommentsWithNames << [User.find(f.user_id).name, f.comments, f.updated_at]
			# Each comment contains [Name, Content, Time]
		end
		allCommentsWithNames
		# are_owners.each do |s|
		# 	usercomments << s
		# end
		# usercomments
	end

	def self.add_new_comment(talk)

	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def index
		@comments = current_user.comments
	end

	def new
		@talk_id = Talk.find(params[:id])
		@comment = Comment.new
		# @comment.talk_id = Talk.find(params[:id])

		respond_to do |format|
  		format.html
  		format.js
  		end
	end

	def create
		@comment = Comment.new
		@comment.comments = params.permit![:comment_content][:comments]
		@comment.talk_id = params.permit![:comment_content][:id]
		@comment.user_id = current_user.id
    	
    	@comment.save!
    	
    	redirect_to :back
    
	end

	def show
	end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_new.html.erb
<%= simple_form_for :talk_content ,:role=> "form", :url => comments_path do|f| %>
<%= f.input :content %>
<% end %>

app/views/comments/index.html.erb
<%= link_to "new comment", new_comment_path%>
	
<%= @comments.each do |c| %>

<% end %>

app/views/comments/new.html.erb
<%= simple_form_for :comments, :role=> "form", :url => comments_path do|f|%>
<%= f.input :content %>
<%= f.submit "Send"%>
<% end %>

app/views/comments/new.js.erb
$('#myModalContent').html("<%= escape_javascript(render :partial => 'new' ) %>");
$('#myModalLabel').html("  <%= escape_javascript(render @talk_content) %>");