config/routes.rb
IOHBack::Application.routes.draw do
  root "home#index"
  get "home/index"
  get "speaker/index"
  get "speaker/new"
  get "talks/index"
  get "admin/index"
    
        
    resources :helpers
    resources :speakers
    resources :first_page
    resources :comments
    resources :process
    resources :home
    resources :admin
    resources :talks
          get 'talks/:id/edit#:category' => 'talks#edit' , :as =>"commenting"
          get 'talks:type' => 'talks#type'
          get 'talks/new/:id' => 'talks#new'
       
       
  devise_for :users
  

end

app/models/talk.rb
class Talk < ActiveRecord::Base
	belongs_to :acadamic_history
    has_many :user_talks
	has_many :users , :through => :user_talks
	has_many :talk_process_lists
	has_many :processes , :through => :talk_process_lists
	has_many :comments
    accepts_nested_attributes_for :talk_process_lists, :reject_if => lambda { |a| a[:process].blank? }, :allow_destroy => true
    accepts_nested_attributes_for :user_talks, :reject_if => lambda { |a| a[:process].blank? }, :allow_destroy => true
    has_attached_file :photography, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/assets/blank.jpg"
    has_attached_file :bg, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/assets/images.jpg"
    
    validates_attachment_content_type :photography, :content_type => %w(image/jpeg image/jpg image/png)
    validates_attachment_content_type :bg, :content_type => %w(image/jpeg image/jpg image/png)
    #validates_attachment_content_type :photogaphy, :content_type => /\Aimage\/.*\Z/
    attr_accessor :process_types, :helper, :processes
    scope :not_finished 
    
    
    def self.not_finished
        @not_finished_list = Array.new
        Talk.all.each do |t|
           if( t.talk_process_lists.where(:finished=>nil).count >0)
                @not_finished_list << t
            end
        end
        @not_finished_list        
    end

    def self.get_type(content)
        if (content == "sign_up")

        end
    end

    def self.on_process(process_name)
        @on_process_list = Array.new
        Talk.all.each do |t|
          current_process =""
            begin
             current_process =  t.talk_process_lists.where(:finished=>nil).order("sequence").first.process_name.to_s 
            rescue
            end
            if(current_process.to_s == process_name.to_s)
                @on_process_list <<t 
            end
        end
        @on_process_list
    end

    def update_process(processes_array)
        processes_temp = processes_array.split(",")
        processes = []
        processes_temp.each do |p|
          processes << p.split("/")
        end
        processes.each do |p|
            if p[1]
                process = self.talk_process_lists.where(:talk_id=>self.id,:all_process_id=>p[0]).first
                process.finished_date = p[1]
                process.finished=true
                process.save!
            end
        end
    end
    def update_user(id)
        if (self.user_talks.find_by_id(id))
          #
        elsif
           self.user_talks.destroy_all
           u = UserTalk.create(:talk_id=>self.id, :user_id=>id)
        end
            
    end
end

   

app/controllers/talks_controller.rb
class TalksController < ApplicationController
  before_filter :authenticate_user!
  def index

  end
  def new
      @process_lists = ProcessList.all
      @acadamic_histories = AcadamicHistory.find(params[:id]) 
      @talk = Talk.new
      user_talks = @talk.user_talks.build
       
  end

  def create
      @talk = Talk.new(params.permit![:talk])
      @talk.save!
      ProcessType.where(:title=>params[:talk][:process_types])[0].all_processes.each do |p|
        TalkProcessList.create(:talk_id => @talk.id, :all_process_id => p.id)
      end
      if(params[:talk][:helper])
        UserTalk.create(:talk_id => @talk.id, :user_id =>  params[:talk][:helper])
      end
      redirect_to talks_path
  end

  def edit
  	@process_lists = ProcessList.all 
    @talk = Talk.find(params[:id])
  	@allUserComments = Comment.where(:talk_id=>params[:id])
    @userComments = Comment.where(talk_id: params[:id])
    # @userComments.name = User.find(f.user_id).name
    #@comment_content = Comment.add_new_comment(:comments)
    @comment = Comment.new
    # @comment.talk_id = params.permit![:id]
    # @comment.save!
    
    respond_to do |format|
      format.html
      format.js
    end
  end

  def type
  	@tc = TalkCreator.new
  	@get_type = params[:type].gsub(/_/, " ") 
    @get_type = @get_type.gsub(/:/, "") 
  	@process_list = AllProcess.all.pluck(:title)
    if current_user.admin?
      @Talks= Talk.all
    else
      @Talks = current_user.talks
    end
  	if (@get_type == "all")
  	@tc_list= Talk.all

   #  elsif (@get_type == "working")
  	# @tc_list = @tc.talk_load(@Talks.not_finished)
  	# else
   #  @tc_list = @tc.talk_load(@Talks.on_process(@get_type))
  	end
  	
  	respond_to do |format|
  		format.html
  		format.js
  	end
  end
  def update
  	@talk = Talk.find(params[:id])
    @talk.update_attributes(params.permit![:talk])
    @talk.save!
    @talk.update_process(params[:talk][:processes])
  	@talk.update_user(params[:talk][:id])
    
  	redirect_to "/talks"

  end
  def download
    @file_object = Talk.find(params[:id])
    redirect_to(@file_object.bg.expiring_url(10))
  end
  def commenting
    @commenting = Comment.new
    @talk = params[:id]
    @category = params[:category]
                        
    respond_to do |format|
      format.html
      format.js
    end
  end
end

app/helpers/talk_helper.rb
module TalkHelper
end

app/views/talks/_commenting.html.erb
<div class="panel panel-primary">
	<div class="panel-heading">
		<h2 class="panel-title">Comments</h2>
	</div>
	<div class="panel-body">

	</div>
</div>

<!--
<%= @talk %>
<%= category %>
<%= simple_form_for :comment ,:role=> "form",:remote=>true, :url => comments_path do|f| %>
<%= f.input :content %>
<%= f.input :talk_id, :input_html => { :value => @talk } %>
<%= f.submit %>
<% end %>
-->

app/views/talks/_helper_data.html.erb
			<div class="panel panel-primary">
				<div class="panel-heading">
					<h2 class="panel-title">Helpers</h2>
				</div>
				<div class="panel-body">
					<div id="helpers_list">
						<div class="row">
							<div class="col-md-4 show" >
								<!-- <h3><#%= f.input :helper, collection: User.all, :label_method => :name, :value_method=>:id , :selected => Talk.first.user_talks.first.nil? ? '': t.user_talks.first.user.id   %></h3> -->
								<h3><%= f.input :helper, collection: User.all, :label_method => :name, :value_method=>:id %></h3>
							</div>
						</div>
					</div>
				</div>
			</div> 
	  	
<script type="text/javascript">
            
				//$(".row.draggable").draggable({revert: "invalid"});
				//$(".row.draggable").droppable();
				//$(".tab-pane" ).sortable();
    			//$(".tab-pane" ).disableSelection();

				$(".helpers").change(function(){
					
					if(this.value=="")
						$(this).parent().next('div').removeClass('show').addClass('hidden');
					else
						$(this).parent().next('div').removeClass('hidden').addClass('show');

				});
				
				


        </script>

app/views/talks/_process_data.html.erb
<div class="panel panel-primary">
	<div class="panel-heading">
		<h2 class="panel-title">Process</h2>
	</div>
	<div class="panel-body">
		<ul class="nav nav-tabs">
		  <li class="active"><a href="#record" data-toggle="tab">Record</a></li>
		  <li><a href="#live" data-toggle="tab">Live Talk</a></li>
		  <li><a href="#article" data-toggle="tab">Article</a></li>
		  </a></li>
		</ul>
		<div class="tab-content">
		  <div class="tab-pane active" id="record">
			 <% @process_lists.where(:process_type=>"record").each do |t| %>
	  		 <div class="row draggable">
		  		<div class="col-md-6">
			  		<%= f.input_field :process,   as: :boolean, boolean_style: :inline, checked_value: true, unchecked_value: false, :include_hidden => false %>
			  		<%= f.label :process, t.title, :class=>"process_name" , boolean_style: :inline,:contentEditable =>"true"%>
		  		</div>	
	  			<div class="col-md-2">
	  				  <%= button_tag "remove" , :class=>"remove_process btn btn-danger btn-xs" %>
	  			</div>
	  			<div class="col-md-3">
	  				<div class="hidden"> 	<%= f.input :process_lists , :input_html => { :class => "datetimepicker form-control"} , label: false%>
	  				</div>
				</div>
			</div>
			<% end %> 
		  </div>
		  <div class="tab-pane" id="live">
	    	 <%  @process_lists.where(:process_type=>"live").each do |t| %>
	  		 <div class="row ">
		  		<div class="col-md-6">
			  		<%= f.input_field :process,   as: :boolean, boolean_style: :inline, checked_value: true, unchecked_value: false, :include_hidden => false %>
			  		<%= f.label :process, t.title, :class=>"process_name" , boolean_style: :inline,:contentEditable =>"true"%>
		  		</div>
	  			<div class="col-md-2">
	  				  <%= button_tag "remove" , :class=>"remove_process btn btn-danger btn-xs" %>
	  			</div>
	  			<div class="col-md-3">
	  				<div class="hidden"> 	<%= f.input :process_lists , :input_html => { :class => "datetimepicker form-control"} , label: false%>
	  				</div>
	  		 
				</div>
			</div>
			<% end %> 
		  </div>
		  <div class="tab-pane" id="article">
	  		 <%  @process_lists.where(:process_type=>"atricle").each do |t| %>
	  		 <div class="row">
		  		<div class="col-md-6">
			  		<%= f.input_field :process,   as: :boolean, boolean_style: :inline, checked_value: true, unchecked_value: false, :include_hidden => false %>
			  		<%= f.label :process, t.title, :class=>"process_name" , boolean_style: :inline,:contentEditable =>"true"%>
		  		</div>
		  		<!--
	  			<div class="col-md-2">
	  				  <#%= button_tag "remove" , :class=>"remove_process btn btn-danger btn-xs" %>
	  			</div>
	  		-->
	  			<div class="col-md-3">
	  				<div class="hidden"> 	<%= f.input :process_lists , :input_html => { :class => "datetimepicker form-control"} , label: false%>
	  				</div>
	  		 
				</div>
			</div>
			<% end %> 
		  </div>
		</div>
	</div>
	
	<!-- <div class="panel-footer">
			<#%= button_tag "add process" , :id=>"add_process", :class=>" btn btn-primary"%> 
	</div>-->
</div>

<script type="text/javascript">
$("#add_process").click(function(){
					$('.process_list').append(
						$('<div>', {'class' : 'row draggable'}).append(
							$('<div>', {'class': 'col-md-6'}).append(
	     						$('<input/>', {'class': 'boolean optional','checked_value':'true', "type" : "checkbox", "value":"true", "unchecked_value":"false"})).append(
	     						$("<label/>" , { "text":"new process" ,"contentEditable":"true","class":"process_name",  'boolean_style':'inline', 'for':'talk_content_process'}))).append(
	     					$('<div>', {'class': 'col-md-2'}).append(
	     						$("<button/>", {"text":"remove", "class":"remove_process btn btn-danger btn-xs"}))).append(
	     					$('<div>', {'class': 'col-md-3'}).append(
							$("<input/>", {"text":"", "class":"datetimepicker form-control"})
	     						)
							
				))
					$(function () {            
                $('.datetimepicker').datepicker({
                    language: 'en',
                    format: 'mm/dd/yyyy',
         			autoclose:true,
         			pickTime: false,
         			todayHighlight: true,
         			todayBtn: "linked"
          	      });
          	  });
					$(".remove_process").click(function(){
					$(this).parent().parent().remove();
					

				});
	     				return false;

				});
</script>

app/views/talks/_submit_data.html.erb
<div class="col-md-12 col-md-offset-11">
<%= f.input :processes, :as=>:hidden %>


<%= f.submit "Update", :class=>"btn btn-primary btn-lg"%>
</div>
<script type="text/javascript">
$('.simple_form.talk').submit(function()
					{
	    				try{
	    	
					     	 
					     //  	var users = $("#helpers_list").children().find(".helpers").map(function() {
	    					// return this.value;
	    					// }).get();
//.this.textContent;


					     	 
					    	}						
					    catch (error)
					    	{}
					    	var processes = $(".process_list").find("li").map(function() {
	    					return $(this).find(".id").get(0).value +"/" + $(this).find(".datetimepicker").val();
							}).get();

					    	document.getElementById("talk_processes").value = processes;
							alert(processes);
					    	
					});
</script>

app/views/talks/_type.html.erb
<table class="table table-hover">
  		<thead>
	  		<tr>
	  			<td>School(Nation)</td>
	  			<td>Major</td>
	  			<td>Degree</td>
	  			<td>Name</td>
	  			<td>Talk Status</td>
	  			<td>Helper</td>
	  			<td>Sign-up Date</td>
	  			<td>Days</td>
	  			<td>Last Activity</td>
	  			<td>Days</td>
	  			<td>TAGS</td>
          <td>Links</td>
	  		</tr>
  		</thead>
  		<tbody>
  			<% @tc_list.each do |tc| %>
  			<% if tc.finished%>
  				<tr class="success" href=''>
  			<% else%>
  				<tr class="" href=''>
  			<% end %>
  				<td><%= tc.main.school %></td>
  				<td><%= tc.main.department %></td>
  				<td><%= tc.main.degree %></td>
  				<td><%= tc.eng_name + " " + tc.chi_name %></td>
  				<td class=" example" data-container="body" data-trigger="hover" data-toggle="popover" data-placement="right" data-content="<%  tc.process.each do |p| %>
  						<%=   p.process_name%> <%=   p.finished_date%><% end	%>">
  						
  					<%= tc.status %>
				</td>
  				<td><%= tc.users %></td>
  				<td><%= tc.sign_up_date %></td>
  				<td><%= tc.days_since_sign_up %></td>
  				<td><%= tc.last_activity_date %></td>
  				<td><%= tc.days_since_last_activity %></td>
  				<td><%= %></td>
          <td><%= link_to "link",edit_talk_path(tc.talk_id) %></td>
  			</tr>
  			<% end %> 
  		</tbody>
	</table>
	<td align=left>Messages</td>
</table>

<script type="text/javascript">
$('.example').popover();
$(".nav.nav-tabs").change();
</script>

app/views/talks/commenting.html.erb
<div id = "myModalContent">
</div>

app/views/talks/edit.html.erb
<style>
  .thumb {
    height: 180px;
    border: 1px solid #000;
    margin: 10px 5px 0 0;
  }
 
</style>

<div class="container">
	<p style="color: green"><%= flash[:notice] %></p>

	<div class="well well-lg">		<!-- comments -->
		<!-- <#% @allUserComments.each do |uc| %> -->
		<% Comment.where(talk_id: @talk.id.to_s).each do |uc| %>
			<div class="row">
			<%#= render :partial => 'commenting', :locals => { :f => f } %>
				<!-- <h3> <span class="label label-success"><#%= uc[0] %>:</span> -->
	 			<!-- <span class="label label-primary"> -->
	 				<!-- <#%= uc[1] %> <font size=1>[<em><#%= uc[2] %></em>]</font> -->
	 			<!-- </span> -->
	 			<h3> <span class="label label-success"><%= User.find(uc.user_id).name %>:</span>
	 			<span class="label label-primary">
	 				<%= uc.comments %> <font size=1>[<em><%= uc.updated_at %></em>]</font>
	 			</span>
			</div>
		<% end %>
		<div class="row">
		<%= simple_form_for :comment_content, :url => { :controller => 'comments', :action => 'create' } do |f| %>
			<%= f.input :id, :as => :hidden, :input_html=> {"value"=>@talk.id}%>
			<%= f.input :comments %>
			<%= f.submit "Send", :class=>"btn btn-primary" %>
		<% end %>
		</div>
	</div>


	<%= simple_form_for :talk, :role=> "form", :url => talk_path(@talk.id), :method=>:put do |f| %>
	
	<%= f.input :id, :id=>"id" ,:as => :hidden %>					
	<div class="row">
		<div class= "col-md-8">
			<div class="row">
				<%= render :partial => 'speaker_data', :locals => { :f => f, :a => @talk.acadamic_history } %>	
				<%= render :partial => 'helper_data', :locals => { :f => f, :t=>@talk } %>	
			</div>	
  		</div>
  		<div class="col-md-4">
			<div class="panel panel-primary">
  				<div class="panel-heading">
   		 			<h3 class="panel-title">Process List</h3>
  				</div>
				<div class="panel-body process_list">
					
						<div class="row">
			  				<!-- <div class="col-md-6"> -->
			  					<ul>
			  					<% @talk.talk_process_lists.each  do |p| %>
			  						<li ><label><input type="checkbox" <%= p.finished ? 'checked' : '' %> class="process_checkbox"  <%= p.finished ? 'disabled' : '' %> > <%=p.all_process.title%><input type="hidden" class="id"  value="<%= p.all_process.id %>"></label> <input type="text" class="datetimepicker  <%= p.finished ? 'show' : 'hide' %>"  <%= p.finished ? 'disabled' : '' %>  value= "<%= p.finished_date%>"  >	</li>
									<% end %>
			  				    </ul>
			  				<!-- </div> -->
			  				
						</div>
					
				</div>
				<!--
			 	<div class="panel-footer">
					<#%= button_tag "add process" , :id=>"add_process", :class=>" btn btn-primary"%>
				</div> -->
			</div>
		</div>
	</div>
	<%= render :partial => 'talk_data', :locals => { :f => f } %>	
	<%= render :partial => 'submit_data', :locals => { :f => f } %>
	<% end %>
</div>





<script type="text/javascript">




          
$('.mymodal').click(function(){
	var type = $(this).data('id');
	document.getElementById("comment_comment_type").value = type;
});
				
						
$("#save_comment").click(function(){
	
	return false;
});

$('.datetimepicker').datepicker({
                    language: 'en',
                    format: 'yyyy-mm-dd',
         			autoclose:true,
         			pickTime: false,
         			todayHighlight: true,
         			todayBtn: "linked"
          	      });
          	  
$('.process_checkbox').click(function(){
    
   if($(this).get(0).checked)
   	  $($(this).parent().parent().find(".datetimepicker")).removeClass("hide").addClass("show");
   else
   	  $(this).parent().parent().find(".datetimepicker").removeClass("show").addClass("hide");

});

</script>
 

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
 	<div class="modal-dialog">
    	<div class="modal-content"></div>
    	<%= simple_form_for :comment ,:role=> "form", :url => comments_path, :method=>:post do|f| %>	
    		<div class="modal-body" >
		
				<div id="myModalContent"> 
        			<%= f.input :comments , :label =>false, :input_html=>{:class=>"form-control", :placeholder=>"Leave a comment"}%>
		    		<%= f.input :comment_type, :as=>:hidden %>
    				<%= f.input :id, :as=>:hidden,  :input_html=>{:value=>@talk.id}%>
    			</div>
			</div>
			<div class="modal-footer">
    			<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	    		<%= f.submit "Save Comment", :class=>"btn btn-primary", :id=>"save_comment", :input_html=>{"data-toggle"=>"modal",  "data-target"=>"#myModal"}%>
	  		</div>
  		<% end %>
    </div>
</div>

app/views/talks/index.html.erb
<div class="container" >


<p style="color: green"><%= flash[:notice] %></p>
<ul class="nav nav-pills">
	<li class="active"><a href="/talks" >All</a></li>
	<li><a href="#schedule" data-toggle="tab">By Schedule</a></li>
	<li><a href="#warning" data-toggle="tab">By Warning</a></li>
	<li><a href="#school" data-toggle="tab">By School</a></li>
	<li><a href="#department" data-toggle="tab">By Deparment</a></li>
	<li><a href="#nation" data-toggle="tab">By Nation</a></li>
</ul>

<div class="tab-content">
	<div class="tab-pane fade in active" id="all"></div>
	<div class="tab-pane fade" id="schedule">
		<ul class="nav nav-pills green">
		  	<% AllProcess.all.each do |p| %>
		  		<% @p_new =  p.title.gsub(/ /, "_") %>
		  		<li> <%= link_to p, "/talks:"+ @p_new, :class=>"category", :remote=>true %></li>
		  	<% end %>
		  	<li><%= link_to "Finished", "/talks:finished", :class=>"category", :remote=>true %></li>
	</div>
	<div class="tab-pane fade" id="warning">
		<ul class="nav nav-pills">
			<li><%= link_to "Signed Up", "/talks:working", :class=>"category", :remote=>true %></li>
  		</ul>
	</div>
	<div class="tab-pane fade" id="school"></div>
	<div class="tab-pane fade" id="department"></div>
	<div class="tab-pane fade" id="nation"></div>
</div>
<div id="content">

	

	

</td>
</table>
<p>
<table class="table table-hover">
  		<thead>
	  		<tr>
	  			<td>Nation</td>
	  			<td>School</td>
	  			<td>Major</td>
	  			<td>Degree</td>
	  			<td>Name</td>
	  			<td>Talk Status</td>
	  			<td>Helper</td>
	  			<td>Sign-up Date</td>
	  			<td>Days</td>
	  			<td>Last Activity</td>
	  			<td>Days</td>
	  			<td>TAGS</td>
	  			<td>link</td>
	  		</tr>
  		</thead>
  		<tbody>
  			<% Talk.all.each do |tc| %>
  			<% if tc.finished%>
  				<tr class="success" href=''>
  			<% else%>
  				<tr class="" href=''>
  			<% end %>
  				<% if tc.acadamic_history %>
  					<td><%= tc.acadamic_history.nation %></td>
	  				<td><%= tc.acadamic_history.school %></td>
  					<td><%= tc.acadamic_history.department %></td>
  					<td><%= tc.acadamic_history.degree %></td>
  					<td>
  						<% if SpeakerProfile.find(tc.acadamic_history.speaker_profile_id) %>
  							<%= SpeakerProfile.find(tc.acadamic_history.speaker_profile_id).eng_name + " " + SpeakerProfile.find(tc.acadamic_history.speaker_profile_id).chi_name %>
  						<% end %> 
					</td>
				<% end %>
  				<!-- <td><#%= tc.acadamic_history.speaker_profile_id %></td> -->
  				<td class=" example" data-container="body" data-trigger="hover" data-toggle="popover" data-placement="right" data-content="<%  tc.talk_process_lists.each do |p| %>
  						<%=   p.process_name%> <%=   p.finished_date%><% end	%>">
  						
  					 <!-- <#%= tc.status %> -->
				</td>
  				<!-- <td><#%= tc.user_talks.first.user.name %></td> -->
  				<!-- 
  				<td><#%= tc.sign_up_date %></td>
  				<td><#%= tc.days_since_sign_up %></td>
  				<td><#%= tc.last_activity_date %></td>
  				<td><#%= tc.days_since_last_activity %></td> -->
  				<td><%= %></td>
  				<td><%= %></td>
  				<td><%= %></td>
  				<td><%= %></td>
  				<td><%= %></td>
  				<td><%= %></td>
  				<td><%= link_to "edit",edit_talk_path(tc.id) %></td>
  			</tr>
  			<% end %> 
  		</tbody>
	</table>
	<td align=left>Messages</td>
</table>
</div>
</div>	
<script type="text/javascript">
$('.example').popover();
$(".category").click(function(){
	
	$("#schedule").find(".active").removeClass('active');
	$(this).parent().addClass('active');
});

</script>

app/views/talks/type.html.erb
<div class="container" >
<table style="border:2px solid rgb(0,0,0); " rules="all" align=right>
	<col span="2" style="background-color: rgb(68,147,18)" width=1000px>
	<tbody  text="#FFFFFF">
		<tr>
			<td align=center width=150><font color="white"><%= link_to "NEW TALK", new_helper_path %> </td>
			<td align=center width=150><font color="white">New Speaker</td>
		

			
		</tr>
	</tbody>
</table>

<p style="color: green"><%= flash[:notice] %></p>
<ul class="nav nav-pills">
			  <li class="active"><a href="/talks:all" >All</a></li>
			  <li><a href="#schedule" data-toggle="tab">By Schedule</a></li>
			  <li><a href="#warning" data-toggle="tab">By Warning</a></li>
			  <li><a href="#school" data-toggle="tab">By School</a></li>
			  <li><a href="#department" data-toggle="tab">By Deparment</a></li>
			  <li><a href="#nation" data-toggle="tab">By Nation</a></li>

			</ul>
<div class="tab-content">
		  <div class="tab-pane fade in active" id="all"></div>
		  <div class="tab-pane fade" id="schedule">
		  		<ul class="nav nav-pills green">
		  			<% @process_list.each do |p| %>
		  			<%	@p_new =  p.gsub(/ /, "_") %>
		  				<li> <%= link_to p, "/talks:"+ @p_new,  :class=>"category", :remote=>true%></li>
		  			<% end %>
		  			  <li><%= link_to "Finished" , "/talks:finished" ,  :class=>"category", :remote=>true%></li>
  				</ul>
 </div>
		  <div class="tab-pane fade" id="warning">
		  	<ul class="nav nav-pills">
				<li><%= link_to "Signed Up" , "/talks:working" ,  :class=>"category", :remote=>true%></li>
  				</ul>
		  </div>
		  <div class="tab-pane fade" id="school"></div>
		  <div class="tab-pane fade" id="department"></div>
		  <div class="tab-pane fade" id="nation"></div>
</div>
<div id="content">

	

	

</td>
</table>
<p>
<table class="table table-hover">
  		<thead>
	  		<tr>
	  			<td>School(Nation)</td>
	  			<td>Major</td>
	  			<td>Degree</td>
	  			<td>Name</td>
	  			<td>Talk Status</td>
	  			<td>Helper</td>
	  			<td>Sign-up Date</td>
	  			<td>Days</td>
	  			<td>Last Activity</td>
	  			<td>Days</td>
	  			<td>TAGS</td>
	  			<td>link</td>
	  		</tr>
  		</thead>
  		<tbody>
  		   <% Talk.all.each do |tc| %>
  			<% if tc.finished%>
  				<tr class="success" href=''>
  			<% else%>
  				<tr class="" href=''>
  			<% end %>
  				<td><%= tc.acadamic_history.school %></td>
  				<td><%= tc.acadamic_history.department %></td>
  				<td><%= tc.acadamic_history.degree %></td>
  				<td><%= tc.acadamic_history.speaker_profile.eng_name + " " + tc.acadamic_history.speaker_profile.chi_name %></td>
  				<td class=" example" data-container="body" data-trigger="hover" data-toggle="popover" data-placement="right" data-content="<%  tc.talk_process_lists.each do |p| %>
  						<%=   p.process_name%> <%=   p.finished_date%><% end	%>">
  						
  					 <!-- <#%= tc.status %> -->
				</td>
  				<td><%= tc.user_talks.first.user.name %></td><!-- 
  				<td><#%= tc.sign_up_date %></td>
  				<td><#%= tc.days_since_sign_up %></td>
  				<td><#%= tc.last_activity_date %></td>
  				<td><#%= tc.days_since_last_activity %></td> -->
  				<td><%= %></td>
  				<td><%= link_to "link",edit_talk_path(tc.id) %></td>
  			</tr>
  			<% end %> 
  		</tbody>
	</table>
	<td align=left>Messages</td>
</table>
</div>
</div>	
<script type="text/javascript">
$('.example').popover();
$(".category").click(function(){
	
	$("#schedule").find(".active").removeClass('active');
	$(this).parent().addClass('active');
});

</script>