config/routes.rb
IOHBack::Application.routes.draw do
  root "home#index"
  get "home/index"
  get "speaker/index"
  get "speaker/new"
  get "talks/index"
  get "admin/index"
    
        
    resources :helpers
    resources :speakers
    resources :first_page
    resources :comments
    resources :process
    resources :home
    resources :admin
    resources :talks
          get 'talks/:id/edit#:category' => 'talks#edit' , :as =>"commenting"
          get 'talks:type' => 'talks#type'
          get 'talks/new/:id' => 'talks#new'
       
       
  devise_for :users
  

end

app/controllers/speakers_controller.rb
class SpeakersController < ApplicationController
  def index
    @speakerlist = SpeakerProfile.all
  end

  def new
  	# @speakers = SpeakerProfile.new 
    @new_speaker = SpeakerProfile.new
    @area = ["North America", "South America", "Asia", "Europe", "Africa", "Oceania"]
    # @subregion = :region
    # @subregion = Country.find_country_by_name(params[:nation])
    # @region = Country.find_country_by_name(:nation)
    @studies = ["Arts & Design","Business & Management", "Media & Communication", "Education", "Engineering", "Humanities & Social Science", "Law", "MBA/EMBA", "Medical & Public Health", "Science", "Other"]
    @achievement = ["Postdoc","PhD","MSc","BSc"]
    3.times do
      acadamic_histories = @new_speaker.acadamic_histories.build
    end      
  end

  def create
  	# @new_speaker = SpeakerCreator.new
    @new_speaker = SpeakerProfile.new(params.permit![:speaker_profile])
    @new_speaker.save!
    #@acadamic = Acadamic_histories.new(params.permit![:new_speaker][:acadamic_histories])
    #@acadamic.save!

  end

  def edit
    @speaker = SpeakerProfile.find(params[:id])
    i = @speaker.acadamic_histories.count
    @area = ["North America", "South America", "Asia", "Europe", "Africa", "Oceania"]
        # @subregion = :region
    # @subregion = Country.find_country_by_name(:nation)


    @studies = ["Arts & Design","Business & Management", "Media & Communication", "Education", "Engineering", "Humanities & Social Science", "Law", "MBA/EMBA", "Medical & Public Health", "Science", "Other"]
    if i < 4
      (3-i).times do
        acadamic_histories = @speaker.acadamic_histories.build
        # acadamic_histories.region = Country.find_country_by_name(@speaker.acadamic_histories.nation.to_s).continent
      end
    end
  end

  def update
    @speaker = SpeakerProfile.find(params[:id])
    @speaker.update_attributes(params.permit![:speaker_profile])
    redirect_to speakers_path
  end
  def show
  end

end

app/helpers/speaker_helper.rb
module SpeakerHelper
end

app/views/speakers/_acadamic_history.erb
<%= f.input :school %>

app/views/speakers/_speaker.html.erb
<link rel="stylesheet" href="../assets/speakers-new.css.scss">

<div class="panel panel-primary left-box">
  <div class="panel-heading"><h4>Basic information</h4></div>
  <div class="panel-body">
  	<div class="row">
		<div class="col-md-5">
  		<h3>Chinese Name <font color="red">*</font></h3>
  		</div>
  		<div class="col-md-6">	
  		<h3><%= f.input_field :chi_name, :style => "width:300px;" %></h3>
  		</div>
	</div>
	
	<div class="row">
		<div class="col-md-5">
		<h3>English Name <font color="red">*</font></h3>
		</div>
		<div class="col-md-6">
		<h3><%= f.input_field :eng_name, :style => "width:300px;" %></h3>
		</div>
	</div>

	<div class="row">
		<div class="col-md-5">
		<h3>Telephone Number</h3>
		</div>
		<div class="col-md-6">
		<h3>
		<h3><%= f.input_field :phone, :style => "width:300px;" %></h3>
		</div>
	</div>

	<div class="row">
		<div class="col-md-5">
		<h3>E-mail</h3>
		</div>
		<div class="col-md-6">
		<h3><%= f.input_field :email, :style => "width:300px;" %></h3> 
		</div>
	</div>
	
	<div class="row">
		<div class="col-md-5">
		<h3>Recommend Name</h3>
		</div>
		<div class="col-md-6">
		<h3><%= f.input_field :recommend_name, :style => "width:300px;" %></h3> 
		</div>
	</div>

	<div class="row">
		<div class="col-md-5">
		<h3>Recommend Telephone</h3>
		</div>
		<div class="col-md-6">
		<h3><%= f.input_field :recommend_phone, :style => "width:300px;" %></h3> 
		</div>
	</div>
	
	<div class="row">
		<div class="col-md-5">
		<h3>Recommend <br>E-mail</h3>
		</div>
		<div class="col-md-6">
		<h3><%= f.input_field :recommend_email, :style => "width:300px;" %></h3> 
		</div>
	</div>

	<div class="row">
		<div class="col-md-5">
		<h3>Recommend Reason</h3>
		</div>
		<div class="col-md-6">
		<h3><%= f.input_field :recommend_reason, :style => "width:300px;" %></h3> 
		</div>
	</div>

  </div>
</div>


<div class="panel panel-primary right-box">
  	<div class="panel-heading"><h4>Other Information</h4></div>
  	
	<div class="panel-body">
		
		

	<div class="row">
		<div class="col-md-5">
		<h3>Operating System (OS)</h3>
		</div>
		<div class="col-md-6">
		<h3><%= f.input_field :OS, :style => "width:300px;" %></h3> 
		</div>
	</div>
	
	<div class="row">
		<div class="col-md-5">
		<h3>Giving Live Talk ?</h3>
		</div>
		<div class="col-md-6">
		<h3><%= f.input_field :give_live_talk, :style => "width:300px;" %></h3> 
		</div>
	</div>

	<div class="row">
		<div class="col-md-5">
		<h3>Current Work</h3>
		</div>
		<div class="col-md-6">
		<h3><%= f.input_field :current_work, :style => "width:300px;" %></h3> 
		</div>
	</div>

	<div class="row">
		<div class="col-md-5">
		<h3>OK time for <br> Live Talk</h3>
		</div>
		<div class="col-md-6">
		<h3><%= f.input_field :time_for_talk, :style => "width:300px;" %></h3> 
		</div>
	</div>

	<div class="row">
		<div class="col-md-5">
		<h3>Other recommend for IOH</h3>
		</div>
		<div class="col-md-6">
		<h3><%= f.input_field :other_recommend, :style => "width:300px;" %></h3> 
		</div>
	</div>


		</div>
		</div>
	</div>
	
</div>
 

<div class="panel panel-primary left-full-box">
  	<div class="panel-heading"><h4>Academic experience</h4></div>
  	<div class="panel-body">
  		<div class="row">
  			<div class="col-md-11">
  			<h4>
  				Please filled in : Country / School / Department / Degree / Graduated Year
  			</h4>
  			</div>
  		</div>
  		<div class="row">
  			<h5><em>
  				<div class="col-md-11">Ex:&nbsp
  				<!-- <input type= "checkbox" checked>&nbsp&nbsp -->
  				<!-- <span class="border"> Tom </span> &nbsp&nbsp -->
  				Country: <span class="border"> United States </span> &nbsp&nbsp
  				University/School: <span class="border"> University of California, Berkeley </span> &nbsp&nbsp
				College: <span class="border"> Engineering </span> &nbsp&nbsp
  				Department: <span class="border"> Computer Science </span> &nbsp&nbsp
  				Degree: <span class="border"> BSc </span> &nbsp&nbsp  
  				Graduated Year: <span class="border"> 2014 </span>
  				</div>
  			</em></h5>
		</div>
		
		<br>
<!-- First Degree Record -->
		<table class="table">
			<thead>
				<tr>
					<th>#</th>
					<!-- <th>Region</th> -->
					<th>Country</th>
		  			<th>University/School</th>
		  			<th>College</th>
			  		<th>Department</th>
		  			<th>Degree</th>
			  		<th>Year</th>
				</tr>
			</thead>
			<% n = 1 %>
			<tbody>
				<%= f.simple_fields_for :acadamic_histories do |builder| %>
				
				<!-- <h5> -->
					<tr>
						<th><%= n %>
							<% if n==1 %><font color="red">*</font><% end %>
						</th>
						<!-- <th><#%= builder.input_field :region, collection: @area.sort, :style => "width:90px;"%></th> -->
						<!-- <th><#%= @region %></th> -->
						<th><%= builder.input_field :nation, collection: Country.all.collect{|a,b| a}.sort , priority_countries: ["United States", "United Kingdom", "Taiwan"], :style => "width:150px;" %></th>
					<!-- Country: <#%= builder.input_field :nation %>&nbsp&nbsp -->
						<th><%= builder.input_field :school, :style => "width:160px;" %></th>
						<th><%= builder.input_field :college, collection: @studies, :style => "width:100px;" %></th>
						<th><%= builder.input_field :department, :style => "width:150px;" %></th>
						<th><%= builder.input_field :degree, collection: @achievement, :style => "width:70px;" %></th>
						<th><%= builder.input_field :year, collection: (1970..2020).reverse_each.to_a, :style => "width:60px;" %></th>
					</tr>
					<% n += 1%> 
					<!-- </h5> -->
				<% end %>
			</tbody>
		</table>
		<%= f.submit "Send", :class=>"btn btn-primary" %>
		<!-- <div style="float:right;"><#%= button_tag "Submit" , :id=>"Submit"%></div> -->
  	</div>
</div>

app/views/speakers/edit.html.erb
<%= simple_form_for @speaker, :role=>"form", :url => speaker_path do |f| %>
	<%= render :partial =>'speaker' , :locals=>{:f=>f} %>
<% end %>

<!-- <script>
//  function checkbox_changer(evt){
//   var checkbox1 = document.getElementById("checkbox1");
//   var checkbox2 = document.getElementById("checkbox2");
//   var checkbox3 = document.getElementById("checkbox3");
//   var checkbox4 = document.getElementById("checkbox4");
  
//   checkbox1.checked = false;
//   checkbox2.checked = false;
//   checkbox3.checked = false;
//   checkbox4.checked = false;

//   evt.target.checked= true;
 
// }
// //document.getElementById("checkbox1").addEventListener("change",checkbox_changer,false);
// //document.getElementById("checkbox2").addEventListener("change",checkbox_changer,false);
// //document.getElementById("checkbox3").addEventListener("change",checkbox_changer,false);
// //document.getElementById("checkbox4").addEventListener("change",checkbox_changer,false);

// // if (checkbox1.text != "")
// $('.new_speaker_creator').submit(function(){
// 	// var  chi_name = document.getElementById("speaker_creator_chi_name");
	 
// 	if (
// 		!(document.getElementById("speaker_creator_chi_name").value
// 		&& document.getElementById("speaker_creator_eng_name").value
// 		&& document.getElementById("speaker_creator_email").value
// 		&& document.getElementById("speaker_creator_acadamic_name1").value
// 		&& document.getElementById("speaker_creator_acadamic_school_abbreviation1").value
// 		&& document.getElementById("speaker_creator_acadamic_department1").value
// 		&& document.getElementById("speaker_creator_acadamic_school1").value
// 		&& document.getElementById("speaker_creator_acadamic_degree1").value
// 		&& document.getElementById("speaker_creator_acadamic_year1").value
// 		)
// 		&&
// 		(document.getElementById("checkbox1").checked == false
// 		&& document.getElementById("checkbox2").checked == false
// 		&& document.getElementById("checkbox3").checked == false
// 		&& document.getElementById("checkbox4").checked == false
// 		)
// 	   )
// 	{
// 		alert("no value");
// 		return false;
// 		//accept 
// 	}
// 	else
// 	{
// 		alert("has value");
// 		return false;
// 		//reject
// 	}
// });
  
</script> -->

<script>
$('#speaker_profile').submit(function(){
	// var  chi_name = document.getElementById("speaker_creator_chi_name");
	// alert("no value"); 
	// return false;
	if (document.getElementById("speaker_profile_chi_name").value &&
		document.getElementById("speaker_profile_eng_name").value &&
		document.getElementById("speaker_profile_acadamic_histories_attributes_0_nation").value &&
		document.getElementById("speaker_profile_acadamic_histories_attributes_0_school").value &&
		document.getElementById("speaker_profile_acadamic_histories_attributes_0_college").value &&
		document.getElementById("speaker_profile_acadamic_histories_attributes_0_department").value &&
		document.getElementById("speaker_profile_acadamic_histories_attributes_0_degree").value &&
		document.getElementById("speaker_profile_acadamic_histories_attributes_0_year").value
		)
	   
	{
		alert("Complete!!");
		return true;
		//accept 
	}
	else
	{
		var info_alert = "Enter the below value:\n";
		if (!document.getElementById("speaker_profile_chi_name").value){
			info_alert += "Chinese Name;\n";
			document.getElementById("speaker_profile_chi_name").style.borderColor="red";
		}
		else
			document.getElementById("speaker_profile_chi_name").style.borderColor="initial";

		if (!document.getElementById("speaker_profile_eng_name").value) {
			info_alert += "English Name;\n";
			document.getElementById("speaker_profile_eng_name").style.borderColor="red";
		}
		else
			document.getElementById("speaker_profile_eng_name").style.borderColor="initial";

		if (!document.getElementById("speaker_profile_acadamic_histories_attributes_0_nation").value){
			info_alert += "Country;\n";
			document.getElementById("speaker_profile_acadamic_histories_attributes_0_nation").style.borderColor="red";
		}
		else
			document.getElementById("speaker_profile_acadamic_histories_attributes_0_nation").style.borderColor="initial";

		if (!document.getElementById("speaker_profile_acadamic_histories_attributes_0_school").value){
			info_alert += "University/School;\n";
			document.getElementById("speaker_profile_acadamic_histories_attributes_0_school").style.borderColor="red";
		}
		else
			document.getElementById("speaker_profile_acadamic_histories_attributes_0_school").style.borderColor="initial";

		if (!document.getElementById("speaker_profile_acadamic_histories_attributes_0_college").value){
			info_alert += "College;\n";
			document.getElementById("speaker_profile_acadamic_histories_attributes_0_college").style.borderColor="red";
		}
		else
			document.getElementById("speaker_profile_acadamic_histories_attributes_0_college").style.borderColor="initial";

		if (!document.getElementById("speaker_profile_acadamic_histories_attributes_0_department").value){
			info_alert += "Department;\n";
			document.getElementById("speaker_profile_acadamic_histories_attributes_0_department").style.borderColor="red";
		}
		else
			document.getElementById("speaker_profile_acadamic_histories_attributes_0_department").style.borderColor="initial";

		if (!document.getElementById("speaker_profile_acadamic_histories_attributes_0_degree").value){
			info_alert += "Degree;\n";
			document.getElementById("speaker_profile_acadamic_histories_attributes_0_degree").style.borderColor="red";
		}
		else
			document.getElementById("speaker_profile_acadamic_histories_attributes_0_degree").style.borderColor="initial";

		if (!document.getElementById("speaker_profile_acadamic_histories_attributes_0_year").value){
			info_alert += "Year;\n";
			document.getElementById("speaker_profile_acadamic_histories_attributes_0_year").style.borderColor="red";
		}
		else
			document.getElementById("speaker_profile_acadamic_histories_attributes_0_year").style.borderColor="initial";
		alert(info_alert);
		return false;
		//reject
	}
	// return false;
});
  
</script>

app/views/speakers/index.html.erb
<div class="container" >

<% n = 0 %>
<% @speakerlist.each do |s| %>
  <% n += 1%>
  <div class="panel-group" id="speakerList">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion" href = #<%=s.id%>>
            <%= n %>. <%= s.eng_name %> (<%= s.chi_name %>)&nbsp&nbsp&nbsp<%= link_to "edit","/speakers/"+ s.id.to_s+"/edit/", {:style => "color:#2B65EC"} %>
          </a>
        </h4>
      </div>
      <div id= <%=s.id%> class="panel-collapse collapse">
        <div class="panel-body">
          <table class="table">
            <thead>
              <tr>
                <th>#</th>
                <!-- <th>Region</th> -->
                <th>Nation</th>
                <th>University/School</th>
                <th>College</th>
                <th>Department</th>
                <th>Degree</th>
                <th>Year</th>
                <th>New Talk</th>
              </tr>
            </thead>
            <tbody>
              <% m = 0 %>
              <% s.acadamic_histories.each do |t| %>
                <% if t.nation || t.school %>
                  <% m += 1%>
                  <tr>
                    <th><%= m %></th>
                    <!-- <th><#%= t.region %></th> -->
                    <th><%= t.nation %></th>
                    <th><%= t.school %></th>
                    <th><%= t.college %></th>
                    <th><%= t.department %></th>
                    <th><%= t.degree %></th>
                    <th><%= t.year %></th>
                    <th><%= link_to "link", "/talks/new/"+ t.id.to_s %></th>
                  </tr>
                <% end %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
<% end %>
</div>
<!-- 	</table> -->

app/views/speakers/new.html.erb
<%= simple_form_for @new_speaker, :role=>"form", :url => speakers_path do |f| %>
	<%= render :partial =>'speaker' , :locals=>{:f=>f} %>
<% end %>

<script>

$('#new_speaker_profile').submit(function(){
	// var  chi_name = document.getElementById("speaker_creator_chi_name");
	// alert("no value"); 
	// return false;
	if (document.getElementById("speaker_profile_chi_name").value &&
		document.getElementById("speaker_profile_eng_name").value &&
		document.getElementById("speaker_profile_acadamic_histories_attributes_0_nation").value &&
		document.getElementById("speaker_profile_acadamic_histories_attributes_0_school").value &&
		document.getElementById("speaker_profile_acadamic_histories_attributes_0_college").value &&
		document.getElementById("speaker_profile_acadamic_histories_attributes_0_department").value &&
		document.getElementById("speaker_profile_acadamic_histories_attributes_0_degree").value &&
		document.getElementById("speaker_profile_acadamic_histories_attributes_0_year").value
		)
	   
	{
		alert("Complete!!");
		return true;
		//accept 
	}
	else
	{
		var info_alert = "Enter the below value:\n";
		if (!document.getElementById("speaker_profile_chi_name").value){
			info_alert += "Chinese Name;\n";
			document.getElementById("speaker_profile_chi_name").style.borderColor="red";
		}
		else
			document.getElementById("speaker_profile_chi_name").style.borderColor="initial";

		if (!document.getElementById("speaker_profile_eng_name").value) {
			info_alert += "English Name;\n";
			document.getElementById("speaker_profile_eng_name").style.borderColor="red";
		}
		else
			document.getElementById("speaker_profile_eng_name").style.borderColor="initial";

		if (!document.getElementById("speaker_profile_acadamic_histories_attributes_0_nation").value){
			info_alert += "Country;\n";
			document.getElementById("speaker_profile_acadamic_histories_attributes_0_nation").style.borderColor="red";
		}
		else
			document.getElementById("speaker_profile_acadamic_histories_attributes_0_nation").style.borderColor="initial";

		if (!document.getElementById("speaker_profile_acadamic_histories_attributes_0_school").value){
			info_alert += "University/School;\n";
			document.getElementById("speaker_profile_acadamic_histories_attributes_0_school").style.borderColor="red";
		}
		else
			document.getElementById("speaker_profile_acadamic_histories_attributes_0_school").style.borderColor="initial";

		if (!document.getElementById("speaker_profile_acadamic_histories_attributes_0_college").value){
			info_alert += "College;\n";
			document.getElementById("speaker_profile_acadamic_histories_attributes_0_college").style.borderColor="red";
		}
		else
			document.getElementById("speaker_profile_acadamic_histories_attributes_0_college").style.borderColor="initial";

		if (!document.getElementById("speaker_profile_acadamic_histories_attributes_0_department").value){
			info_alert += "Department;\n";
			document.getElementById("speaker_profile_acadamic_histories_attributes_0_department").style.borderColor="red";
		}
		else
			document.getElementById("speaker_profile_acadamic_histories_attributes_0_department").style.borderColor="initial";

		if (!document.getElementById("speaker_profile_acadamic_histories_attributes_0_degree").value){
			info_alert += "Degree;\n";
			document.getElementById("speaker_profile_acadamic_histories_attributes_0_degree").style.borderColor="red";
		}
		else
			document.getElementById("speaker_profile_acadamic_histories_attributes_0_degree").style.borderColor="initial";

		if (!document.getElementById("speaker_profile_acadamic_histories_attributes_0_year").value){
			info_alert += "Year;\n";
			document.getElementById("speaker_profile_acadamic_histories_attributes_0_year").style.borderColor="red";
		}
		else
			document.getElementById("speaker_profile_acadamic_histories_attributes_0_year").style.borderColor="initial";
		alert(info_alert);
		return false;
		//reject
	}
	// return false;
});
  
</script>

app/views/speakers/test.html.erb
<%= simple_form_for @new_speaker, :role=>"form", :url=> speakers_path do |f| %>

<%= f.input :bio %>
		
			<%= f.simple_fields_for  :acadamic_histories do |builder| %>
				<%= render "acadamic_history", :f=>builder %>
			<% end %>
		
<%= button_tag "Submit" , :id=>"Submit"%>
<% end%>