config/routes.rb
IOHBack::Application.routes.draw do
  root "home#index"
  get "home/index"
  get "speaker/index"
  get "speaker/new"
  get "talks/index"
  get "admin/index"
    
        
    resources :helpers
    resources :speakers
    resources :first_page
    resources :comments
    resources :process
    resources :home
    resources :admin
    resources :talks
          get 'talks/:id/edit#:category' => 'talks#edit' , :as =>"commenting"
          get 'talks:type' => 'talks#type'
          get 'talks/new/:id' => 'talks#new'
       
       
  devise_for :users
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IOHBack</title>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-inverse " >
    <title>Myapp2</title>
    <div class="container">
      <div class="navbar-header">
        <%= link_to image_tag("ioh-logo.png", size: "245x150" ),  "/home/index" %> 
      </div>
      <div class="navbar-collapse collapse">
        <div class="navbar-form navbar-right">
          <!-- <table style="border:1px solid rgb(0,0,0); " rules="all" align=right> -->
          <table align=right>
            <col span="2" style="background-color: white" width=1000px>
            <tbody text="#FFFFFF">
              <tr>
                <td align=center width=80><font color="white"><%= link_to "Talk List", talks_path%></td>
                <td align=center width=80><font color="white"><%= link_to "New Talk", new_helper_path %> </td>
                <td align=center width=100><font color="white"><%= link_to "New Speaker", new_speaker_path %></td>
                <td align=center width=100><font color="white"><%= link_to "Speaker List", speakers_path%></td>
                
                <% if current_user %>
                  <td align=center width=80><font color="white"><%= link_to('修改密碼', edit_registration_path(:user)) %> </td>
                  <td align=center width=40><font color="white"><%= link_to('登出', destroy_user_session_path, :method => :delete) %> </td>
                <% else %>
                  <td align=center width=60><font color="white"><%= link_to('註冊', new_registration_path(:user)) %> </td>
                  <td align=center width=40><font color="white"><%= link_to('登入', new_session_path(:user)) %></td>
                <% end %>
              </tr>
            </tbody>
          </table>

        </div>
      </div>
   

    </div>
  </div>

<%= yield %>

</body>
</html>